Sets
i        /Player1, Player2, Player3/
j        /Tech1, Tech2/
;

Parameters
alpha_n0    /100/
alpha_n1    /105/
alpha_n2    /95/
alpha_n3    /110/
alpha_n4    /108/
alpha_n5    /106/
alpha_n6    /93/
alpha_n7    /100/
alpha_n8    /100/
alpha_n9    /100/
alpha_n10    /100/
alpha_n11    /100/
alpha_n12    /100/
alpha_n13    /100/
alpha_n14    /100/
alpha_n15    /100/
alpha_n16    /100/
alpha_n17    /100/
alpha_n18    /100/
alpha_n19    /100/
alpha_n20    /100/
alpha_n21    /100/
alpha_n22    /100/
alpha_n23    /100/
alpha_n24    /100/
alpha_n25    /100/
alpha_n26    /100/
alpha_n27    /100/
alpha_n28    /100/
alpha_n29    /100/
alpha_n30    /100/
alpha_n31    /100/
alpha_n32    /100/
alpha_n33    /100/
alpha_n34    /100/
alpha_n35    /100/
alpha_n36    /100/
alpha_n37    /100/
alpha_n38    /100/
alpha_n39    /100/
alpha_n40    /100/
alpha_n41    /100/
alpha_n42    /100/
alpha_n43    /100/
alpha_n44    /100/
alpha_n45    /100/
alpha_n46    /100/
alpha_n47    /100/
alpha_n48    /100/
alpha_n49    /100/
alpha_n50    /100/
alpha_n51    /100/
alpha_n52    /100/
alpha_n53    /100/
alpha_n54    /100/
alpha_n55    /100/
alpha_n56    /100/
alpha_n57    /100/
alpha_n58    /100/
alpha_n59    /100/
alpha_n60    /100/
alpha_n61    /100/
alpha_n62    /100/
beta        /0.75/
delta1      /0.9708738/
delta2      /0.9425959/
delta3      /0.9151417/
delta4      /0.8884870/
delta5      /0.8626088/
nu          /0.9/
rho         /0.025/
;



Table K0(i,j)
                      Tech1     Tech2
          Player1      25       15
          Player2      8        20
          Player3      0        10
;


Parameter c(j)           /
                         Tech1    2
                         Tech2    1
                         /;

Parameter F(j)          /
                         Tech1   2
                         Tech2   2.1

                        /;